# ----
# Site

title: SEONOLOGY FOOD
url: https://blog.seonology.com
baseurl:
google_analytics_key:

logo: /siteicon.png
description: Photography site for seonology.
author:
  name: SEON
  email: dark.pearl.nst@gmail.com
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/2005/2005-04-20.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
